version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: veera-leave-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin834
      POSTGRES_DB: Leave
    ports:
      - "5475:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: veera-leave-backend
    restart: always
    ports:
      - "3077:3077"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: Leave
      DB_PASSWORD: Veera@0134
      DB_PORT: 5432

  frontend:
    build: ./Frontend
    container_name: veera-leave-frontend
    restart: always
    ports:
      - "8106:80"

  hr:
    build: ./HR
    container_name: veera-leave-hr
    restart: always
    ports:
      - "8107:80"

volumes:
  pgdata:

